config/routes.rb
Rails.application.routes.draw do
  root to: 'twmaps#show', id: 'millifes2'

  # auth
  get '/auth/:provider/callback', :to => 'sessions#callback'
  post '/auth/:provider/callback', :to => 'sessions#callback'
  get '/auth/failure' => 'sessions#failure'
  get '/logout' => 'sessions#destroy', :as => :logout

  resources :twmaps, only: [:show]
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.screen_name = auth['info']['nickname']
      user.name = auth['info']['name']
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login_required
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    else
      redirect_to root_path
    end

  end

  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :login_required, except: [:index]

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback
    auth = request.env['omniauth.auth']
    user = User.find_by_provider_and_uid(auth['provider'], auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    session[:access_token] = auth['credentials']['token']
    session[:access_secret] = auth['credentials']['secret']
    redirect_to root_path
  end

  def failure
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/twitter_controller.rb
class TwitterController < ApplicationController
  before_action :login_required

  def friends
    @friend_list = friend_list
  end

  def millimas_friends
    require 'nkf'

    list = friend_list
    @millifes_list = []

    list.each do |friend|
      next unless (NKF.nkf('-wXZ', friend.name) =~ /ミリフェス/)
      m = /P(?<spnum>\d+)(?<spalp>[abAB]+)?/.match(friend.name)
      next if m.nil?
      @millifes_list << { friend: friend, space: m['spnum'], alphabet: (m['spalp'].presence || 'ab') }
    end
    @millifes_list.sort! { |a, b| a[:space].to_i <=> b[:space].to_i }
  end

  private
  def friend_list
    access_key = session[:access_token]
    access_secret = session[:access_secret]

    cli = Twitter::REST::Client.new(
      consumer_key:        Settings.twitter.consumer_key,
      consumer_secret:     Settings.twitter.consumer_secret,
      access_token:        access_key,
      access_token_secret: access_secret
    )

    begin
      list = []
      cli.friend_ids.each_slice(100).each do |slice|
        cli.users(slice).each do |friend|
          list << friend
        end
      end
      list
    rescue Twitter::Error::TooManyRequests => error
      []
    end
  end
end

app/controllers/twmaps_controller.rb
class TwmapsController < ApplicationController
  def show
    if params[:id] != 'millifes2'
      redirect_to root_path
      return
    end
    @millifes_list = []
    return unless current_user
    require 'nkf'

    begin
      list = friend_list
    rescue Twitter::Error::Unauthorized => error
      redirect_to logout_path
      return
    end

    list.each do |friend|
      next unless (NKF.nkf('-wXZ', friend.name) =~ /ミリフェス/)
      m = /P(?<spnum>\d+)(?<spalp>[abAB]+)?/.match(friend.name)
      next if m.nil?

      # for security reason, remote url cannot convert canvas to dataurl...
      require 'open-uri'

      open("public/images/tmp/#{friend.id}", 'wb') do |file|
        file << open(friend.profile_image_url).read
      end

      @millifes_list << { friend: friend, local_icon_url: "tmp/#{friend.id}", space: m['spnum'], alphabet: (m['spalp'].presence || 'ab') }
    end
    @millifes_list.sort! { |a, b| a[:space].to_i <=> b[:space].to_i }
  end

  private
  def friend_list
    access_key = session[:access_token]
    access_secret = session[:access_secret]

    cli = Twitter::REST::Client.new(
      consumer_key:        Settings.twitter.consumer_key,
      consumer_secret:     Settings.twitter.consumer_secret,
      access_token:        access_key,
      access_token_secret: access_secret
    )

    begin
      list = []
      cli.friend_ids.each_slice(100).each do |slice|
        cli.users(slice).each do |friend|
          list << friend
        end
      end
      list
    rescue Twitter::Error::TooManyRequests => error
      []
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/twitter_helper.rb
module TwitterHelper
end

app/views/home/index.html.erb
<% if current_user %>
  <p><%= current_user.name %>でログイン中</p>
  <ul>
    <li><%= link_to 'ミリフェスMAPの作成', twmap_path('millifes2') %></li>
    <li><%= link_to 'ログアウト', logout_path %></li>
  </ul>
<% else %>
  <ul>
    <li><%= link_to 'ログイン', '/auth/twitter' %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MlmapGenerator" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body data-controller="<%= params[:controller] %>">

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'MlmapGenerator', root_path, class: 'navbar-brand' %>
        <div class='navbar-collapse collapse navbar-responsive-collapse'>
          <ul class='nav navbar-nav navbar-right'>
            <li>
              <%- if current_user %>
                <%= link_to "ログアウト(#{current_user.name})", logout_path %>
              <% else %>
                <%= link_to 'ログイン', '/auth/twitter' %>
              <%- end %>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

  </body>
</html>

app/views/twmaps/_friend_list.erb
<table class="table table-bordered" style='font-size: .8em; width: 100%;'>
  <thead>
    <tr>
      <th>#</th>
      <th>UserInfo</th>
    </tr>
  </thead>
  <tbody>
    <%- friend_list.each do |ml| %>
      <tr class="mlmap-row" id="row-<%= ml[:friend].id %>" data-target-id="<%= ml[:friend].id %>" data-spnum="<%= ml[:space] %>" data-spalp="<%= ml[:alphabet] %>">
        <td rowspan='3'>
          <div style='text-align: center'>
            P<span style='font-weight: bold'><%= ml[:space] %></span>-<%= ml[:alphabet] %><br />
            <%= label_tag "visible-icon-#{ml[:friend].id}" do %>
              <img class='mlmap-user-icon' id='mlmap-user-icon-<%= ml[:friend].id %>' style='width: 30px; height: 30px;' alt='<%= ml[:friend].name %>' />
            <%- end %>
            <br />
            <%= check_box_tag("visible-icon-#{ml[:friend].id}", true, true, class: 'toggle-icon', data: { target_id: ml[:friend].id })%>
          </div>
        </td>
        <td>
          <%= link_to ml[:friend].url.to_s, target: '_blank' do%>
            @<%= ml[:friend].screen_name %>
          <%- end %>
          /
          <span style='font-size: .8em'>
            <%- if ml[:friend].website? %>
              <%= link_to ml[:friend].name, ml[:friend].website.to_s, target: '_blank' %>
            <%- else %>
              <%= ml[:friend].name %>
            <%- end %>
          </span>
        </td>
      </tr>
      <tr>
        <td style='font-size: .8em'><%= ml[:friend].description %></td>
      </tr>
      <tr>
        <td><%= text_area_tag("memo-#{ml[:friend].id}", "@#{ml[:friend].screen_name}", style: 'width: 100%') %></td>
      </tr>
    <%- end %>
  </tbody>
</table>

app/views/twmaps/_introduction.erb
<div class="panel panel-default">
  <div class="panel-body">
    <h4>これは何？</h4>
    <p>
      来る7/12(日)に東京ビッグサイトで開催される<%= link_to 'MILLION FESTIV@L!! 2', 'https://www.aoboo.jp/neo/item/p0015.html', target: '_blank' %>の
      サークルマップを生成する<b>超ごく一部の層に向けた(そして7/12までしか意味のない)ツール</b>です。利用するにはTwitterログインが必要です。
    </p>
    <p><%= link_to 'Twitterでログイン', '/auth/twitter', class: 'btn btn-primary' %></p>
    <h4>ログインすると何が起こるの？</h4>
    <p>
      あなたがフォローしている人のうち、ミリフェスに出すっぽい人を抽出して白地図上に配置します。一応メモっぽいこともできます。
      <%= link_to '@t3_', 'https://twitter.com/t3_', target: '_blank' %>さんが作ってるような自分用の地図が欲しくて作りました。
      詳しくは<%= link_to '作者のブログ記事', 'http://www.atelier-nodoka.net/2015/07/mlmaps-generator/', target: '_blank' %>を参照してください。利用環境はPCを想定して作っています。
    </p>
    <h4>ご要望・フィードバック等</h4>
    <p><%= link_to '@treby006', 'https://twitter.com/treby006', target: '_blank' %>まで。応援ください。</p>
  </div>
</div>
<%= render partial: 'twitter_widget' %>

app/views/twmaps/_twitter_widget.erb
<a class="twitter-timeline" href="https://twitter.com/hashtag/%E3%83%9F%E3%83%AA%E3%83%95%E3%82%A7%E3%82%B9%E3%83%9E%E3%83%83%E3%83%97" data-widget-id="618124478376062976">#ミリフェスマップ のツイート</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/twmaps/show.erb
<div class='row'>
  <div class='col-lg-3'>
    <div class='row' style='height: 710px; overflow: scroll;'>
      <%- unless current_user %>
        <%= render partial: 'introduction' %>
      <%- else %>
        <%= render partial: 'friend_list', locals: { friend_list: @millifes_list } %>
      <%- end %>
    </div>
  </div>
  <div class='col-lg-9'>
    <canvas style='border:1px solid gray' id='mlmap' width='800px' height='708px'></canvas>
  </div>
</div>
<%- if current_user %>
  <div class='row'>
    <div class='col-lg-3'>
      <div class='row'>
        <%= render partial: 'twitter_widget' %>
      </div>
    </div>
    <div class='col-lg-9' style='text-align: center'>
      <a href='#' id='mlmap-output-button' class='btn btn-primary' role='button'>作成したマップ画像を開く！</a>
    </div>
  </div>
<%- end %>